language: node_js
node_js:
  - 5.0
cache:
  directories:
    - "node_modules"
    - "src/third_party"
addons:
  firefox: "latest"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libnotify-bin
env:
  matrix:
    - "DISPLAY=:99.0 CXX=g++-4.8"

before_script:
  - "sh -e /etc/init.d/xvfb start"
